import type { Metadata } from "next";
import "./globals.css";
import { NavigationMenuDemo } from "@/Componenets/ui/navbar";
import { Exo } from "next/font/google";
import ToastProvider from "@/Componenets/ui/Toastify";
import Providers from "./auth/Providers";
import ProvidersReactQuery from "./ReactQuerieProvider/provider";
const exoSans = Exo({
  subsets: ["latin"],
  variable: "--font-exo-sans",
});

const exoMono = Exo({
  subsets: ["latin"],
  variable: "--font-exo-mono",
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
  icons: {
    icon: "/WhatsApp Image 2026-05-07 at 11.24.48 PM.jpeg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exoSans.variable} ${exoMono.variable} antialiased`}>
        <Providers>
          <ProvidersReactQuery>
            <NavigationMenuDemo />
            <div className="pt-17">{children}</div>
            <ToastProvider />
          </ProvidersReactQuery>
        </Providers>
      </body>
    </html>
  );
}